name: Publish NPM Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies  
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build --filter "mrbd-ui-kit"

      - name: Publish to NPM
        working-directory: packages/mrbd-ui-kit
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
